cat  \
        styles/site-variables.colors.css \
        styles/common.blocks/general.css \
        styles/common.blocks/button/button.css \
        styles/common.blocks/form/form.css \
        styles/common.blocks/menu/menu.css \
        styles/common.blocks/popup/popup.css \
        styles/common.blocks/input-group/input-group.css \
        styles/common.blocks/input-group/input-group_minimalist.css \
        styles/common.blocks/text-editor/text-editor.css \
        styles/common.blocks/image-upload/image-upload.css \
        styles/common.blocks/book-cover/book-cover.css \
        styles/common.blocks/book-cover/book-cover_list-item.css \
        styles/common.blocks/book-cover/book-cover_thumbnail.css \
        styles/common.blocks/book-cover/home-page.book-cover.css \
        styles/other.css \
        styles/book.page.css \
        styles/reader.css \
        > styles/min.css
