export default [
    "Abey Dawn",
    "Arial",
    "Arial Black",
    "Arial Bold",
    "Courier New",
    "Georgia",
    "Inter",
    "Latha",
    "Microsoft Sans Serif",
    "monospace",
    "Mv Boli",
    "Ostrich Rounded",
    "Palatino Linotype",
    "Palatino Linotype Bold",
    "Palatino Linotype Bold Italic",
    "Palatino Linotype Italic",
    "Roman",
    "SpaceMono",
    "Tahoma",
    "Tahoma Bold",
    "Times New Roman",
    "Times New Roman Bold",
    "Times New Roman Bold Italic",
    "Times New Roman Italic",
]
