export default [
"Arial",
"Arial Black",
"Arial Bold",
"Arial Bold Italic",
"Arial Italic",
"Comic Sans MS",
"Comic Sans MS Bold Courier 10,12,15",
"Courier New",
"Courier New Bold",
"Courier New Bold Italic",
"Courier New Italic",
"Estrangelo Edessa",
"Franklin Gothic Medium",
"Franklin Gothic Medium",
"Italic",
"Gautami",
"Georgia",
"Georgia Bold",
"Georgia Bold Italic",
"Georgia Italic Impact",
"Latha",
"Lucida Console",
"Lucida Sans Unicode",
"Microsoft Sans Serif",
"Modern MS Sans Serif 8,10,12,14,18,24",
    "monospace",
"MS Serif 8,10,12,14,18,24",
"Mv Boli",
"Palatino Linotype",
"Palatino Linotype Bold",
"Palatino Linotype Bold Italic",
"Palatino Linotype Italic",
"Roman",
"Script",
"Small Fonts",
"Symbol",
"Symbol 8,10,12,14,18,24",
"Tahoma",
"Tahoma Bold",
"Times New Roman",
"Times New Roman Bold",
"Times New Roman Bold Italic",
"Times New Roman Italic",
"Trebuchet MS",
"Trebuchet MS Bold",
"Trebuchet MS Bold Italic",
"Trebuchet MS Italic",
"Tunga",
"Verdana",
"Verdana Bold",
"Verdana Bold Italic Verdana Italic",
"Webdings",
"WingDings",
"WST_Czech",
"WST_Engl",
"WST_Fren",
"WST_Germ",
"WST_Ital",
"WST_Span",
"WST_Swed",
]
